pipeline:
  test:
    image: node:${NODE_VERSION}
    commands:
      - yarn
      - yarn test
  build:
    image: docker
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --tls=false -t enteam/enfunc:build-$DRONE_COMMIT_SHA .
      - if [[ "$DRONE_COMMIT_SHA" == "master" ]]; then docker tag enteam/enfunc:build-$DRONE_COMMIT_SHA enteam/enfunc --tls=false; fi
      - docker push enteam/enfunc:build-$DRONE_COMMIT_SHA --tls=false
      - if [[ "$DRONE_COMMIT_SHA" == "master" ]]; then docker push enteam/enfunc --tls=false; fi

services:
  docker:
    image: docker:dind
    command: [ "--storage-driver=vfs", "--tls=false" ]
    privileged: true

matrix:
  include:
    - NODE_VERSION: 8