version: '2'
services: 
  mongo:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    networks: 
      - enfunc
    volumes:
      - mongodata:/data/db
  redis:
    networks: 
      - enfunc
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/var/lib/redis
    restart: always
  enfunc:
    networks: 
      - enfunc
    image: enteam/enfunc
    environment: 
      - MONGODB_URI=mongodb://mongo/enfunc
      - REDIS_URI=redis://redis
    ports:
      - 3000:3000
    restart: always

volumes: 
  mongodata:
  redisdata:
networks: 
  enfunc: